//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmoothDataProcessor
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmoothDataProcessor.DataClientGeneratorSoap")]
    public interface DataClientGeneratorSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<SmoothDataProcessor.HelloWorldResponse> HelloWorldAsync(SmoothDataProcessor.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProcessData", ReplyAction="*")]
        System.Threading.Tasks.Task<SmoothDataProcessor.ProcessDataResponse> ProcessDataAsync(SmoothDataProcessor.ProcessDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLookUp", ReplyAction="*")]
        System.Threading.Tasks.Task<SmoothDataProcessor.GetLookUpResponse> GetLookUpAsync(SmoothDataProcessor.GetLookUpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DwnLdLFE", ReplyAction="*")]
        System.Threading.Tasks.Task DwnLdLFEAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSchema", ReplyAction="*")]
        System.Threading.Tasks.Task<SmoothDataProcessor.GetSchemaResponse> GetSchemaAsync(SmoothDataProcessor.GetSchemaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public SmoothDataProcessor.HelloWorldRequestBody Body;
        
        public HelloWorldRequest()
        {
        }
        
        public HelloWorldRequest(SmoothDataProcessor.HelloWorldRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody
    {
        
        public HelloWorldRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmoothDataProcessor.HelloWorldResponseBody Body;
        
        public HelloWorldResponse()
        {
        }
        
        public HelloWorldResponse(SmoothDataProcessor.HelloWorldResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody()
        {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult)
        {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessData", Namespace="http://tempuri.org/", Order=0)]
        public SmoothDataProcessor.ProcessDataRequestBody Body;
        
        public ProcessDataRequest()
        {
        }
        
        public ProcessDataRequest(SmoothDataProcessor.ProcessDataRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcessDataRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestData;
        
        public ProcessDataRequestBody()
        {
        }
        
        public ProcessDataRequestBody(string requestData)
        {
            this.requestData = requestData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmoothDataProcessor.ProcessDataResponseBody Body;
        
        public ProcessDataResponse()
        {
        }
        
        public ProcessDataResponse(SmoothDataProcessor.ProcessDataResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcessDataResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ProcessDataResult;
        
        public ProcessDataResponseBody()
        {
        }
        
        public ProcessDataResponseBody(string ProcessDataResult)
        {
            this.ProcessDataResult = ProcessDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLookUpRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLookUp", Namespace="http://tempuri.org/", Order=0)]
        public SmoothDataProcessor.GetLookUpRequestBody Body;
        
        public GetLookUpRequest()
        {
        }
        
        public GetLookUpRequest(SmoothDataProcessor.GetLookUpRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLookUpRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string lookUpId;
        
        public GetLookUpRequestBody()
        {
        }
        
        public GetLookUpRequestBody(string lookUpId)
        {
            this.lookUpId = lookUpId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLookUpResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLookUpResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmoothDataProcessor.GetLookUpResponseBody Body;
        
        public GetLookUpResponse()
        {
        }
        
        public GetLookUpResponse(SmoothDataProcessor.GetLookUpResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLookUpResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetLookUpResult;
        
        public GetLookUpResponseBody()
        {
        }
        
        public GetLookUpResponseBody(string GetLookUpResult)
        {
            this.GetLookUpResult = GetLookUpResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSchemaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSchema", Namespace="http://tempuri.org/", Order=0)]
        public SmoothDataProcessor.GetSchemaRequestBody Body;
        
        public GetSchemaRequest()
        {
        }
        
        public GetSchemaRequest(SmoothDataProcessor.GetSchemaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetSchemaRequestBody
    {
        
        public GetSchemaRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSchemaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSchemaResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmoothDataProcessor.GetSchemaResponseBody Body;
        
        public GetSchemaResponse()
        {
        }
        
        public GetSchemaResponse(SmoothDataProcessor.GetSchemaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSchemaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSchemaResult;
        
        public GetSchemaResponseBody()
        {
        }
        
        public GetSchemaResponseBody(string GetSchemaResult)
        {
            this.GetSchemaResult = GetSchemaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface DataClientGeneratorSoapChannel : SmoothDataProcessor.DataClientGeneratorSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class DataClientGeneratorSoapClient : System.ServiceModel.ClientBase<SmoothDataProcessor.DataClientGeneratorSoap>, SmoothDataProcessor.DataClientGeneratorSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DataClientGeneratorSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(DataClientGeneratorSoapClient.GetBindingForEndpoint(endpointConfiguration), DataClientGeneratorSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataClientGeneratorSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DataClientGeneratorSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataClientGeneratorSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DataClientGeneratorSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataClientGeneratorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmoothDataProcessor.HelloWorldResponse> SmoothDataProcessor.DataClientGeneratorSoap.HelloWorldAsync(SmoothDataProcessor.HelloWorldRequest request)
        {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmoothDataProcessor.HelloWorldResponse> HelloWorldAsync()
        {
            SmoothDataProcessor.HelloWorldRequest inValue = new SmoothDataProcessor.HelloWorldRequest();
            inValue.Body = new SmoothDataProcessor.HelloWorldRequestBody();
            return ((SmoothDataProcessor.DataClientGeneratorSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmoothDataProcessor.ProcessDataResponse> SmoothDataProcessor.DataClientGeneratorSoap.ProcessDataAsync(SmoothDataProcessor.ProcessDataRequest request)
        {
            return base.Channel.ProcessDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmoothDataProcessor.ProcessDataResponse> ProcessDataAsync(string requestData)
        {
            SmoothDataProcessor.ProcessDataRequest inValue = new SmoothDataProcessor.ProcessDataRequest();
            inValue.Body = new SmoothDataProcessor.ProcessDataRequestBody();
            inValue.Body.requestData = requestData;
            return ((SmoothDataProcessor.DataClientGeneratorSoap)(this)).ProcessDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmoothDataProcessor.GetLookUpResponse> SmoothDataProcessor.DataClientGeneratorSoap.GetLookUpAsync(SmoothDataProcessor.GetLookUpRequest request)
        {
            return base.Channel.GetLookUpAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmoothDataProcessor.GetLookUpResponse> GetLookUpAsync(string lookUpId)
        {
            SmoothDataProcessor.GetLookUpRequest inValue = new SmoothDataProcessor.GetLookUpRequest();
            inValue.Body = new SmoothDataProcessor.GetLookUpRequestBody();
            inValue.Body.lookUpId = lookUpId;
            return ((SmoothDataProcessor.DataClientGeneratorSoap)(this)).GetLookUpAsync(inValue);
        }
        
        public System.Threading.Tasks.Task DwnLdLFEAsync()
        {
            return base.Channel.DwnLdLFEAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmoothDataProcessor.GetSchemaResponse> SmoothDataProcessor.DataClientGeneratorSoap.GetSchemaAsync(SmoothDataProcessor.GetSchemaRequest request)
        {
            return base.Channel.GetSchemaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmoothDataProcessor.GetSchemaResponse> GetSchemaAsync()
        {
            SmoothDataProcessor.GetSchemaRequest inValue = new SmoothDataProcessor.GetSchemaRequest();
            inValue.Body = new SmoothDataProcessor.GetSchemaRequestBody();
            return ((SmoothDataProcessor.DataClientGeneratorSoap)(this)).GetSchemaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DataClientGeneratorSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.DataClientGeneratorSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DataClientGeneratorSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:55510/DataClientGenerator.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.DataClientGeneratorSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:55510/DataClientGenerator.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            DataClientGeneratorSoap,
            
            DataClientGeneratorSoap12,
        }
    }
}
